### ISSUE TITLE
ProxyConfiguration option for using JVM default proxy selector

### ISSUE THREAD

**Issue by gatesn** [palantir/conjure-java-runtime-api#160]
I would like a way to configure a service to use the JVM's default proxy selector. Currently if `ProxyConfiguration#type = HTTP`, it bypasses the system settings. It looks like `ProxyConfiguration#type = MESH` uses the default selector, but it seems wrong to configure that.

What are your thoughts on either:

1. Introduce a new `type = DEFAULT`
1. Default `hostAndPort` to `System.getenv("http_proxy")` if not set for `type = HTTP`

**Comment by gatesn** [comment]
Ping on this. Would like to know which option, if any, I should go ahead with?

**Comment by LorenzoMartini** [comment]
Solved in #535
